/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface WavePortalInterface extends ethers.utils.Interface {
  functions: {
    "getTopWaver()": FunctionFragment;
    "getTotalWaves()": FunctionFragment;
    "isWaver(address)": FunctionFragment;
    "newWaver(address)": FunctionFragment;
    "updateWaverWaveCount(address)": FunctionFragment;
    "wave()": FunctionFragment;
    "waverList(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getTopWaver",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalWaves",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "isWaver", values: [string]): string;
  encodeFunctionData(functionFragment: "newWaver", values: [string]): string;
  encodeFunctionData(
    functionFragment: "updateWaverWaveCount",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "wave", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "waverList",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getTopWaver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalWaves",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isWaver", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "newWaver", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateWaverWaveCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "wave", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "waverList", data: BytesLike): Result;

  events: {};
}

export class WavePortal extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: WavePortalInterface;

  functions: {
    getTopWaver(
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber] & { waverAddress: string; waveCount: BigNumber }
    >;

    getTotalWaves(overrides?: CallOverrides): Promise<[BigNumber]>;

    isWaver(
      waverAddress: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    newWaver(
      waverAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateWaverWaveCount(
      waverAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    wave(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    waverList(arg0: BigNumberish, overrides?: CallOverrides): Promise<[string]>;
  };

  getTopWaver(
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber] & { waverAddress: string; waveCount: BigNumber }
  >;

  getTotalWaves(overrides?: CallOverrides): Promise<BigNumber>;

  isWaver(waverAddress: string, overrides?: CallOverrides): Promise<boolean>;

  newWaver(
    waverAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateWaverWaveCount(
    waverAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  wave(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  waverList(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  callStatic: {
    getTopWaver(
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber] & { waverAddress: string; waveCount: BigNumber }
    >;

    getTotalWaves(overrides?: CallOverrides): Promise<BigNumber>;

    isWaver(waverAddress: string, overrides?: CallOverrides): Promise<boolean>;

    newWaver(waverAddress: string, overrides?: CallOverrides): Promise<void>;

    updateWaverWaveCount(
      waverAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    wave(overrides?: CallOverrides): Promise<void>;

    waverList(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    getTopWaver(overrides?: CallOverrides): Promise<BigNumber>;

    getTotalWaves(overrides?: CallOverrides): Promise<BigNumber>;

    isWaver(
      waverAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    newWaver(
      waverAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateWaverWaveCount(
      waverAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    wave(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    waverList(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getTopWaver(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getTotalWaves(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isWaver(
      waverAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    newWaver(
      waverAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateWaverWaveCount(
      waverAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    wave(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    waverList(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
