/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { WavePortal } from "./WavePortal";

export { WavePortal__factory } from "./factories/WavePortal__factory";
